openapi: "3.0.0"
info:
  title: eCommerce API
  description: API documentation for eCommerce application
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/ecommerce
tags:
  - name: Prices
    description: Operations regarding product prices
paths:
  /prices:
    $ref: 'prices/prices.yml#/prices'

components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string